name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:

  docker-build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Cache tooling binaries
      uses: actions/cache@v2
      id: cache-tooling-binaries
      with:
        path: ./container-root-x86_64.tgz
        key: ${{ hashFiles('tooling_versions.env') }}

    - name: Download tooling binaries
      if: steps.cache-tooling-binaries.outputs.cache-hit != 'true'
      run: |
        ./get-sources.sh

    - name: Build container image
      run: |
        docker build -f ./Dockerfile .
